#!/bin/sh

cd `dirname $0`

(
	cd test || exit 1

	echo '#include <unistd.h>' >| data.h

	ls * | sed '/[.][hc]$/d' |
	while read fn
	do
		printf 'extern const char test_%s[];\n' "$fn" >> data.h
		printf 'extern const size_t test_%s_size;\n' "$fn" >> data.h

		printf '#include "test/data.h"\n' >| $fn.c
		printf 'const size_t test_%s_size = %d;\n' "$fn"  `wc -c <"$fn"` >> "$fn.c"
		printf 'const char test_%s[] = ' "$fn" >> "$fn.c"

		touch /tmp/line.$$
		while :; do
			rm /tmp/line.$$
			dd status=none bs=80 count=1 of=/tmp/line.$$
			test -s /tmp/line.$$ || break
			printf '"' >> "$fn.c"
			sed '
s/\\/\\\\/g
s/\x00/\\000/g
s/\x07/\\007/g
s/\x1b/\\033/g
s/\x0d/\\015/g
s/"/\\042/g
s/\x08/\\010/g
$!s/$/\\012/
			' /tmp/line.$$ | tr -d '\n' >> "$fn.c"
			printf '"\n' >> "$fn.c"
		done < "$fn" 
		printf ';\n' >> "$fn.c"
	done
)

	cc -x c -std=c99 -I. -D_POSIX_C_SOURCE=200809L \
	 -Wformat \
	 -o session \
	 session.c \
	 shared.c \
	 test/*.c \
	 third_party/dtach/*.c \
	 -lutil ||
		exit 1

if ! ctags=`which ctags-exuberant`; then
	echo '`sudo apt install exuberant-ctags` to make tags file' 2>&1
else
	find . -path ./third_party/websocketd -prune -o -type f \( \
		-name \*.h -o -name \*.c \
	\) -print >/tmp/tag_files.$$

	$ctags --format=1 `cat /tmp/tag_files.$$`
fi

echo 'running session test...' >&2
if ! ./session test >|/tmp/testout.$$; then
	echo 'test session proc terminated with error' >&2
	exit 1
fi

err=

if ! diff -u passing_test_output /tmp/testout.$$
then
	echo "build succeeded but tests failed; to update:
	cp /tmp/testout.$$ $PWD/passing_test_output"
	err=1
fi >&2

# We pipe this into wc first because grep may not recognize a null byte
# as expected.
if </tmp/testout.$$ tr -d '\n -~' | wc -c | grep -q '[^0]'
then
	echo 'TEST OUTPUT HAS NON-PRINTABLE OR CONTROL CHAR(S) !!1!' >&2
	err=1
fi

test -n "$err" && exit 1
make -C third_party/websocketd || exit 1
