#!/bin/sh

cmd_scratch=/tmp/compile_commands_$$.json

cd `dirname $0`

make -C third_party/websocketd

echo '{' >| compile_commands.json

	clang -x c -std=c99 -I. -D_POSIX_C_SOURCE=200809L -MJ $cmd_scratch \
	 -o session \
	 session.c \
	 shared.c \
	 third_party/dtach/*.c \
	 -lutil ||
		exit 1
	cat $cmd_scratch >> compile_commands.json
	rm $cmd_scratch

echo '}' >> compile_commands.json

# if ! ctags=`which ctags-exuberant`; then
# 	echo '`sudo apt install exuberant-ctags` to make tags file' 2>&1
# else
# 	$ctags --format=1 -R .
# fi

echo 'running session test...' >&2
./session test >|/tmp/testout.$$

if ! diff -u passing_test_output /tmp/testout.$$
then
	echo "build succeeded but tests failed; to update:
	cp /tmp/testout.$$ $PWD/passing_test_output"
	exit 1
fi >&2
