#!/bin/sh

cmd_scratch=/tmp/compile_commands_$$.json

cd `dirname $0`

echo '{' >| compile_commands.json

	clang -x c -std=c99 -I. -D_POSIX_C_SOURCE=200809L -MJ $cmd_scratch \
	 -fsanitize=address \
	 -o session \
	 session.c \
	 shared.c \
	 third_party/dtach/*.c \
	 -lutil ||
		exit 1
	cat $cmd_scratch >> compile_commands.json
	rm $cmd_scratch

echo '}' >> compile_commands.json

if ! ctags=`which ctags-exuberant`; then
	echo '`sudo apt install exuberant-ctags` to make tags file' 2>&1
else
	find . -path ./third_party/websocketd -prune -o -type f \( \
		-name \*.h -o -name \*.c \
	\) -print >/tmp/tag_files.$$

	$ctags --format=1 `cat /tmp/tag_files.$$`
fi

echo 'running session test...' >&2
if ! ./session test >|/tmp/testout.$$; then
	echo 'test session proc terminated with error' >&2
	exit 1
fi

err=

if ! diff -u passing_test_output /tmp/testout.$$
then
	echo "build succeeded but tests failed; to update:
	cp /tmp/testout.$$ $PWD/passing_test_output"
	err=1
fi >&2

# We pipe this into wc first because grep may not recognize a null byte
# as expected.
if </tmp/testout.$$ tr -d '\n -~' | wc -c | grep -q '[^0]'
then
	echo 'TEST OUTPUT HAS NON-PRINTABLE OR CONTROL CHAR(S) !!1!' >&2
	err=1
fi

test -n "$err" && exit 1
make -C third_party/websocketd || exit 1
