#!/bin/sh

cd `dirname $0`
export WERMDIR=`pwd`

wsd=$HOME/.local/websocketd/websocketd

passenv=/tmp/werm_passenv.$$

cat >| $passenv << EOF
WERMDIR,DISPLAY,PATH,HOME,SHELL,DBUS_SESSION_BUS_ADDRESS,XDG_RUNTIME_DIR,LANG
LANGUAGE
EOF

env | sed '
	/^\(LC_[A-Z]*\)=.*/!d
	s//\1/
' >> $passenv

set -x
third_party/websocketd/websocketd \
	--passenv `tr '\n' , <$passenv` \
	--cgidir=cgi \
	--staticdir=. \
	"$@" \
	"$PWD/session"
