#!/bin/sh

cd `dirname $0`
export WERMDIR=`pwd`

wsd=$HOME/websocketd/websocketd
test -f $wsd || wsd=websocketd

$wsd --passenv WERMDIR,DISPLAY,PATH,HOME,SHELL,DBUS_SESSION_BUS_ADDRESS,XDG_RUNTIME_DIR\
	--cgidir=cgi \
	--staticdir=. \
	"$@" \
	./session
