#!/bin/sh
# Copyright 2023 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd `dirname $0`
export WERMDIR=`pwd`

passenv=/tmp/werm_passenv.$$

cat >| $passenv << EOF
WERMDIR,DISPLAY,PATH,HOME,SHELL,DBUS_SESSION_BUS_ADDRESS,XDG_RUNTIME_DIR,LANG
LANGUAGE,USER
EOF

env | sed '
	/^\(LC_[A-Z]*\)=.*/!d
	s//\1/
' >> $passenv

set -x
# We run the `session` binary with the fully-qualified path so that the argv[0]
# string can be overwritten with long strings.
# We run websocketd with the fully-qualified paths because we will cd to $HOME
# right before exec'ing it, so that spawned shells will start at home for free.
exec "$PWD/session" serve \
	"$PWD/third_party/websocketd/websocketd" \
	--passenv `tr '\n' , <$passenv` \
	--cgidir="$PWD/cgi" \
	--staticdir="$PWD" \
	"$@" \
	"$PWD/session"
