#!/bin/sh

cat <<EOF
Content-type: text/html


<!DOCTYPE html>
<meta charset='utf-8'/>
<html>
<head>
	<title>Attach</title>
</head>
<body style="font-family: monospace">
<big>Common</big>
<ul>
EOF

termid=4201
for dir in /s/cros2/src werm; do
	for i in `seq 5`; do
		printf '
		<li><a href="/?termid=%s&pream=exec%%20ow%%20%s%%0d">
		%s (%d)</a href>
		' $termid $dir $dir $i
		termid=$(( termid + 1 ))
	done
done

cat <<EOF
</ul>
<big>Active sessions</big>
<table>
EOF

ls /tmp/dtach.* | sed 's/^.*[.]//' |
while read sess
do
	printf '<tr>
		<td style="padding-right:20pt">[<strong>%s</strong>]
		<td><a href="/?termid=%s">%s</a>
		</tr>\n' \
		$sess \
		$sess \
		"`cat /tmp/title.$sess`"
done

cat <<EOF
</table>
</body>
EOF
