#!/bin/sh
# Copyright 2023 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

cat <<EOF
Content-type: text/html


<!DOCTYPE html>
<meta charset='utf-8'/>
<meta http-equiv="expires" content="-1" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Cache-Control" content="no-cache" />
<html>
<head>
	<title>attach[$SERVER_PORT]</title>
<style>
td.loose {
	padding-right:20pt;
}
h1 {
	margin-top: 7pt;
	margin-bottom:8pt;
	padding-bottom:8pt;
	border-bottom: solid 1px yellow;
}
.ephemeral-sessions {
	padding-top: 1em;
	font-size: 0.8em;
}
.column {
	padding-top: 6pt;
	padding-bottom: 6pt;
	padding-left: 24pt;
	padding-right: 24pt;
	border: 2px solid yellow;
}
.newsessin-list {
	margin-top: 1em;
	padding-left: 0;
	list-style-type: none;
}
a {
	color: white;
	text-decoration: none;
}
.feedback {
	padding: 0.5em;
	font-size: 0.7em;
}
</style>
</head>
<body style="font-family: monospace; font-size: 14px;  background-color: black; color: #8f8;">
<table style="border: 2px solid yellow; border-collapse: collapse">

<tr>
<td nowrap class=column style="vertical-align:top">
<h1>New</h1>
EOF

$WERMSRCDIR/session newsessinlinks | LC_ALL=C sort

cat <<EOF
<td nowrap class=column style="vertical-align: top">
<h1>Existing</h1>
<table>
EOF

# We redundantly verify a part of the path printed by lsof within awk because I
# have seen lsof return totally different paths (also sockets) in the case of
# files that are deleted but still open: Linux 6.3.11, lsof 4.95.0, Debian
lsof -Fn $WERMSRCDIR/var/socks/prs%* |
awk '
/^n.*\/var\/socks\/prs%/ {
	sub(/^n.*\/var\/socks\/prs%/, "", $1);
	count[$1] += 1;
}
END {
	for (k in count)
		printf "%s %d\n", k, count[k];
}' |
# Sort according to ASCII - this puts ~ at the end of the list.
LC_ALL=C sort |
while read sess cnt
do
	att='&nbsp;'
	test $cnt = 1 || att='*'
	printf '<tr>
		<td class="loose">[<strong>%s</strong>]
		<td>%s
		<td><a class='restore-link' href="/?termid=%s">%s</a>
		</tr>\n' \
		$sess \
		"$att" \
		$sess \
		$sess
done

cat <<EOF
</table>
<div class=ephemeral-sessions>Ephemeral sessions:
EOF
find $WERMSRCDIR/var/socks/eph%* | wc -l
cat <<EOF
</div>
</tr>
<tr>
<td colspan=2 class=feedback>
Werm issue tracker on <a href="https://github.com/google/werm">GitHub</a><br>
Other feedback welcome at <a href="matvore@chromium.org">matvore@chromium.org</a>
</tr>
</table>

<script>
console.log('prep document onload');
window.onload = function() {
console.log('document onload');
var es, title, i, auxjs, int;

es = document.getElementsByClassName('restore-link');

for (i = 0; i < es.length; i++) {
	int = es[i].innerText;
	title = (localStorage.getItem('title-' + int) || '').trim();
	if (title) es[i].innerText = title;
}
};
</script>
</body>
</html>
EOF
