#!/bin/sh
# Copyright 2023 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

cat $WERMSRCDIR/third_party/hterm/client.js

echo -n '
// TM API implementation for JS
#include "tm.js"

// Code fully converted to compile as C or JavaScript using TM API
#include "teng"
#include "third_party/hterm/teng"

// Code that can pass through the preprocessor and may use TM defines and is a
// candidate for moving into `teng`. This will eventually be deleted.
#include "third_party/hterm/engine.js"
' | cpp -P -I$WERMSRCDIR "$@"
