#!/bin/sh

echo Content-type: text/javascript
echo

cat $WERMDIR/third_party/hterm/client.js

do_cpp () {
	cpp -P -I$WERMDIR/third_party/hterm/include_js "$@"
}

# Code fully converted to compile as C or JavaScript using TM defines
do_cpp $WERMDIR/third_party/hterm/teng

# Code that can pass through the preprocessor and may use TM defines and is a
# candidate for moving into `teng`. This will eventually be deleted.
do_cpp $WERMDIR/third_party/hterm/engine.js

# Stuff that must be defined for transitory engine.js code.
cat $WERMDIR/third_party/hterm/clientpost.js
