#!/bin/sh

echo Content-type: text/javascript
echo

cat $WERMDIR/third_party/hterm/client.js

echo -n '
// TM API implementation for JS
#include "tm.js"

// Code fully converted to compile as C or JavaScript using TM API
#include "third_party/hterm/teng"

// Code that can pass through the preprocessor and may use TM defines and is a
// candidate for moving into `teng`. This will eventually be deleted.
#include "third_party/hterm/engine.js"
' | cpp -P -I$WERMDIR "$@"
