#!/bin/sh
# Copyright 2023 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

termid=`echo $QUERY_STRING | sed '
	/\(.*&\|^\)termid=\([^&]*\)\(&.*\|$\)/!d
	s//\2/
'`

cat <<EOF
Content-type: text/html


<!DOCTYPE html>
<meta charset='utf-8'/>
<meta http-equiv="expires" content="-1" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Cache-Control" content="no-cache" />
<html>
<head>
<title>LOG [$termid]</title>
<style>
body {
	background: black;
	margin-left: 0px;
	margin-top: 0px;
	margin-bottom: 0px;
}
#content {
	resize: none;
	background: black;
	white-space: pre;
	overflow: auto;
	color: white;
	width: calc(100vw - 1em);
	height: calc(100vh - 1em);
	margin-left: 0.2em;
	margin-top: 0.2em;
}
</style>
<script>
function contentel() { return document.getElementById('content'); }

function initcontentview()
{
	var el = contentel(), loc;

	if (window.scrollbackcontent) {
		el.value = window.scrollbackcontent;
		el.scrollTop = 0;
		el.setSelectionRange(0, 0);
	}
	else {
		el.scrollTop = el.scrollHeight;
		el.setSelectionRange(el.value.length, el.value.length);
	}

	el.focus();
}

document.onkeydown = function(ev)
{
	if (ev.key != 'Enter') return;
	if (ev.metaKey || ev.shiftKey || ev.ctrlKey || ev.altKey) return;

	var el = contentel();

	/* Automatically omit the last newline in selection. */
	if (el.value[el.selectionEnd-1] == '\n') el.selectionEnd--;

	if (el.selectionEnd != el.selectionStart) document.execCommand('copy');

	ev.preventDefault();
	window.close();
};

</script>
</head>
<body onload="initcontentview()">
<textarea spellcheck=false id=content>
EOF

# Use find rather than ls to avoid extra matches when $termid is empty.
find "$WERMSRCDIR/var" \
	-mindepth 4 \
	-name "$termid" \
	-type f \
	-not -path '*/hist/*' \
| sort \
| tail -n 2 \
| while read fn; do
	echo "--- SCROLLBACK $fn ---"
	cat "$fn"
done \
| sed '
	s/&/\&amp;/g
	s/</\&lt;/g
	s/>/\&gt;/g
'

cat <<'EOF'
</textarea>
</body>
</html>
EOF
