#!/bin/sh
# Copyright 2024 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

echo window.wermhosttitle = \""$WERMHOSTTITLE"\"\;

cat <<'EOF'
if (!window.wermhosttitle)
	window.wermhosttitle = location.host.replace(/^localhost:/, ':');
EOF
